################################################################################
#
# AMCL
#
################################################################################

AMCL_VERSION = 4.7.0
AMCL_SITE = $(call github,milagro-crypto,milagro-crypto-c,$(AMCL_VERSION))
AMCL_LICENSE = Apache-2.0
AMCL_LICENSE_FILES = LICENSE
AMCL_INSTALL_STAGING = YES

AMCL_CONF_OPTS += -DAMCL_INCLUDE_SUBDIR=amcl
AMCL_CONF_OPTS += -DBUILD_BENCHMARKS=OFF
AMCL_CONF_OPTS += -DWORD_SIZE=$(if $(BR2_ARCH_IS_64),64,32)

AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_ANSSI),ANSSI,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_BLS383),BLS383,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_BLS461),BLS461,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_BN254),BN254,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_BN254CX),BN254CX,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_BRAINPOOL),BRAINPOOL,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_C25519),C25519,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_C41417),C41417,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_ED25519),ED25519,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_FP256BN),FP256BN,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_FP512BN),FP512BN,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_GOLDILOCKS),GOLDILOCKS,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_HIFIVE),HIFIVE,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NIST256),NIST256,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NIST384),NIST384,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NIST521),NIST521,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NUMS256E),NUMS256E,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NUMS256W),NUMS256W,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NUMS384E),NUMS384E,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NUMS384W),NUMS384W,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NUMS512E),NUMS512E,)
AMCL_CURVE += $(if $(BR2_PACKAGE_AMCL_CURVE_NUMS512W),NUMS512W,)

AMCL_CURVE_COMMASEPARATED += $(subst $(space),$(comma),$(strip $(AMCL_CURVE)))
AMCL_CONF_OPTS += -DAMCL_CURVE=$(AMCL_CURVE_COMMASEPARATED)

AMCL_RSA += $(if $(BR2_PACKAGE_AMCL_RSA_2048),2048,)
AMCL_RSA += $(if $(BR2_PACKAGE_AMCL_RSA_3072),3072,)
AMCL_RSA += $(if $(BR2_PACKAGE_AMCL_RSA_4096),4096,)

AMCL_RSA_COMMASEPARATED += $(subst $(space),$(comma),$(strip $(AMCL_RSA)))
AMCL_CONF_OPTS += -DAMCL_RSA=$(AMCL_RSA_COMMASEPARATED)

AMCL_CONF_OPTS += -DBUILD_MPIN=$(if $(BR2_PACKAGE_AMCL_MPIN),ON,OFF)
ifeq ($(BR2_PACKAGE_AMCL_MPIN),y)
	AMCL_CONF_OPTS += -DAMCL_MAXPIN=$(BR2_PACKAGE_AMCL_MPIN_MAXPIN)
	AMCL_CONF_OPTS += -DAMCL_PBLEN=$(BR2_PACKAGE_AMCL_MPIN_PBLEN)
endif

AMCL_CONF_OPTS += -DBUILD_WCC=$(if $(BR2_PACKAGE_AMCL_WCC),ON,OFF)

$(eval $(cmake-package))
