################################################################################
#
# ECDAA
#
################################################################################

ECDAA_VERSION = v0.10.0
ECDAA_SITE = $(call github,xaptum,ecdaa,$(ECDAA_VERSION))
ECDAA_LICENSE = Apache-2.0
ECDAA_LICENSE_FILES = LICENSE
ECDAA_INSTALL_STAGING = YES
ECDAA_SUPPORTS_IN_SOURCE_BUILD = NO

ECDAA_DEPENDENCIES += amcl
ECDAA_DEPENDENCIES += $(if $(BR2_PACKAGE_ECDAA_TPM_SUPPORT),xaptum-tpm,)

ECDAA_CURVES += $(if $(BR2_PACKAGE_ECDAA_CURVE_BLS383),BLS383,)
ECDAA_CURVES += $(if $(BR2_PACKAGE_ECDAA_CURVE_BN254),BN254,)
ECDAA_CURVES += $(if $(BR2_PACKAGE_ECDAA_CURVE_BN254CX),BN254CX,)
ECDAA_CURVES += $(if $(BR2_PACKAGE_ECDAA_CURVE_FP256BN),FP256BN,)
ECDAA_CURVES_COMMASEPARATED += $(subst $(space),$(comma),$(strip $(ECDAA_CURVES)))

ECDAA_CONF_OPTS += -DECDAA_CURVES=$(ECDAA_CURVES_COMMASEPARATED)

ifeq ($(BR2_PACKAGE_ECDAA_TPM_SUPPORT),y)
	ECDAA_CONF_OPTS += -DECDAA_TPM_SUPPORT=ON
else
	ECDAA_CONF_OPTS += -DECDAA_TPM_SUPPORT=OFF
endif

$(eval $(cmake-package))
